apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate-{{.Values.databaseMigrationSuffix}}
spec:
  template:
    spec:
      initContainers:
      - name: check-db-ready
        image: {{.Values.imageRegistry}}/postgres:alpine
        command: ['sh', '-c',
          'until pg_isready -h $DATABASE_HOSTNAME -p 5432;
          do echo waiting for database; sleep 2; done;']
        env:
          - name: DATABASE_HOSTNAME
            value: {{ .Release.Name }}-{{.Values.databaseHostnameSuffix}}
      containers:
      - name: {{ .Release.Name }}-migrate-{{.Values.databaseMigrationSuffix}}
        image: {{.Values.imageRegistry}}/myapp:{{.Values.myappTag}}
        command: ["python",  "manage.py", "migrate"]
        env:
          - name: DATABASE_HOSTNAME
            value: {{ .Release.Name }}-{{.Values.databaseHostnameSuffix}}
      restartPolicy: Never
  backoffLimit: 4