apiVersion: v1
kind: Pod
metadata:
  name: myapp-database
  labels:
    app: myapp-database
spec:
  containers:
  - name: myapp-database
    image: localhost/postgres:alpine
    imagePullPolicy: Always
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_PASSWORD
        value: postgres
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_DB
        value: myapp_db
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: myapp-database
  namespace: default
  labels:
    app: myapp-database
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: myapp-database
  type: ClusterIP
status:
  loadBalancer: {}